#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = ["mlx-lm==0.31.3"]
# ///
"""Replace placeholder <think>…</think> blocks in train_chat.jsonl / val_chat.jsonl
with real reasoning traces generated by Qwen3.6-27B (MLX 4-bit).

Uses mlx_lm.batch_generate for continuous batching — keeps the GPU saturated
with up to 32 prompts in flight at once, with wired memory pinning for the
weights."""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path

os.environ.setdefault("PYTHONUNBUFFERED", "1")
sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

from mlx_lm import load
from mlx_lm.generate import batch_generate
from mlx_lm.sample_utils import make_sampler

ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = ROOT / "models" / "Qwen3.6-27B"
DATA_FILES = [
    ROOT / "data" / "processed" / "train_chat.jsonl",
    ROOT / "data" / "processed" / "val_chat.jsonl",
]

MAX_TOKENS = 1024
TEMPERATURE = 0.6
CHUNK_SIZE = 64                # records per batch_generate call (and per checkpoint)
COMPLETION_BATCH_SIZE = 32     # in-flight prompts (continuous batching slots)
PREFILL_BATCH_SIZE = 8

THINK_END_ID = 248069          # </think>
IM_END_ID = 248046             # <|im_end|>

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)

GUIDANCE = (
    "Think step by step in <think>...</think> tags about: "
    "(1) what pattern the macro call matches, "
    "(2) what Lisp constructs are needed, "
    "(3) how to handle quasiquote/unquote, "
    "(4) variable capture concerns, "
    "(5) the overall structure of the defmacro form. "
    "Then provide the defmacro."
)


def warn(msg: str) -> None:
    print(f"warning: {msg}", file=sys.stderr)


def load_jsonl(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def write_jsonl(path: Path, rows: list[dict]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
    tmp.replace(path)


def split_assistant(content: str) -> tuple[str | None, str]:
    m = THINK_RE.search(content)
    if not m:
        return None, content
    tail = content[m.end():].lstrip("\n")
    return m.group(1).strip("\n"), tail


def already_real(content: str) -> bool:
    inner, _ = split_assistant(content)
    if inner is None:
        return False
    return not inner.lstrip().startswith("Analyzing the macro call pattern:")


def build_prompt_ids(tokenizer, system: str, user: str) -> list[int]:
    messages = [
        {
            "role": "system",
            "content": system.strip() + "\n\n" + GUIDANCE,
        },
        {"role": "user", "content": user},
    ]
    return tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
    )


def extract_think(raw: str) -> str | None:
    """Pull the reasoning text out of a model response. The chat template injects
    `<think>\\n` into the prompt tail and we stop on `</think>`, so the response is
    typically the bare reasoning text."""
    text = (raw or "").strip()
    if not text:
        return None

    m = THINK_RE.search(text)
    if m:
        return m.group(1).strip("\n").strip()

    if "</think>" in text:
        return text.split("</think>", 1)[0].strip("\n").strip() or None

    head = re.split(r"\n```|\n\(defmacro", text, maxsplit=1)[0].strip()
    if head and len(head) > 20:
        return head
    return None


def render_thinking(content: str) -> str:
    return f"<think>\n{content.strip()}\n</think>"


def collect_targets(rows: list[dict]) -> list[tuple[int, dict, str]]:
    """Return list of (row_index, asst_msg, tail_after_placeholder) for rows that
    still hold a placeholder. The system+user messages are read directly off the
    row when building the prompt."""
    out = []
    for i, row in enumerate(rows):
        msgs = row.get("messages") or []
        asst = next((m for m in msgs if m["role"] == "assistant"), None)
        if not asst or already_real(asst["content"]):
            continue
        placeholder, tail = split_assistant(asst["content"])
        if placeholder is None:
            continue
        out.append((i, asst, tail))
    return out


def process_file(
    path: Path,
    model,
    tokenizer,
    sampler,
    stats: dict,
) -> None:
    rows = load_jsonl(path)
    targets = collect_targets(rows)
    print(
        f"\nprocessing {path.name}: {len(rows)} records, "
        f"{len(targets)} need traces, "
        f"{len(rows) - len(targets)} already done"
    )
    stats["skipped_existing"] += len(rows) - len(targets)

    if not targets:
        write_jsonl(path, rows)
        return

    overall_t0 = time.time()
    for chunk_start in range(0, len(targets), CHUNK_SIZE):
        chunk = targets[chunk_start : chunk_start + CHUNK_SIZE]

        prompts: list[list[int]] = []
        for row_idx, _asst, _tail in chunk:
            row = rows[row_idx]
            sys_msg = next(m for m in row["messages"] if m["role"] == "system")
            usr_msg = next(m for m in row["messages"] if m["role"] == "user")
            prompts.append(
                build_prompt_ids(tokenizer, sys_msg["content"], usr_msg["content"])
            )

        t0 = time.time()
        try:
            batch = batch_generate(
                model,
                tokenizer,
                prompts=prompts,
                max_tokens=MAX_TOKENS,
                sampler=sampler,
                completion_batch_size=COMPLETION_BATCH_SIZE,
                prefill_batch_size=PREFILL_BATCH_SIZE,
                verbose=False,
            )
            texts = batch.texts
        except Exception as exc:  # noqa: BLE001
            warn(f"batch_generate failure on chunk {chunk_start}: {exc!r}")
            stats["failures"] += len(chunk)
            continue

        chunk_ok = 0
        for (row_idx, asst, tail), raw in zip(chunk, texts):
            trace = extract_think(raw)
            if not trace:
                stats["failures"] += 1
                continue
            rebuilt = render_thinking(trace)
            if tail:
                rebuilt = f"{rebuilt}\n{tail}"
            asst["content"] = rebuilt
            stats["successes"] += 1
            stats["trace_chars_total"] += len(trace)
            chunk_ok += 1

        write_jsonl(path, rows)

        elapsed = time.time() - t0
        done = chunk_start + len(chunk)
        total_elapsed = time.time() - overall_t0
        avg_per_record = total_elapsed / done if done else 0.0
        eta = (len(targets) - done) * avg_per_record
        print(
            f"  {done}/{len(targets)}  chunk_ok={chunk_ok}/{len(chunk)}  "
            f"chunk_time={elapsed:.1f}s ({len(chunk)/elapsed:.2f} rec/s)  "
            f"eta={eta/60:.1f}m  peak_mem={batch.stats.peak_memory:.1f}GB"
        )

    print(f"finished {path.name}")


def count_remaining_placeholders(path: Path) -> int:
    rows = load_jsonl(path)
    return sum(
        1
        for row in rows
        for m in row.get("messages", [])
        if m["role"] == "assistant" and not already_real(m["content"])
    )


def main() -> None:
    if not MODEL_PATH.exists():
        print(f"error: model not found at {MODEL_PATH}", file=sys.stderr)
        sys.exit(1)

    print(f"loading model from {MODEL_PATH}…")
    t_load = time.time()
    model, tokenizer = load(str(MODEL_PATH))
    print(f"model loaded in {time.time() - t_load:.1f}s")

    # batch_generate seeds its stop set from tokenizer.eos_token_ids, so register
    # </think> there to get early-stop on the closing reasoning tag.
    tokenizer.add_eos_token(THINK_END_ID)
    print(f"eos token ids in use: {sorted(tokenizer.eos_token_ids)}")

    sampler = make_sampler(temp=TEMPERATURE)

    stats = {
        "successes": 0,
        "failures": 0,
        "skipped_existing": 0,
        "trace_chars_total": 0,
    }

    overall_t0 = time.time()
    for path in DATA_FILES:
        if not path.exists():
            warn(f"missing data file {path}; skipping")
            continue
        process_file(path, model, tokenizer, sampler, stats)
    elapsed = time.time() - overall_t0

    remaining = sum(count_remaining_placeholders(p) for p in DATA_FILES if p.exists())
    avg_len = (
        stats["trace_chars_total"] / stats["successes"] if stats["successes"] else 0.0
    )

    print("\n=== SUMMARY ===")
    print(f"successful traces:      {stats['successes']}")
    print(f"failed (placeholder):   {stats['failures']}")
    print(f"skipped (already real): {stats['skipped_existing']}")
    print(f"placeholders remaining: {remaining}")
    print(f"avg trace length:       {avg_len:.0f} chars")
    print(f"total elapsed:          {elapsed/60:.1f} min")


if __name__ == "__main__":
    main()
